# Generated by Django 5.0.4 on 2024-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='data_prestito',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
