# Generated by Django 4.2.11 on 2024-04-13 15:45

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='restituzioni',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
