# Generated by Django 4.2.11 on 2024-04-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_alter_utente_restituzioni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
