# Generated by Django 4.2.11 on 2024-04-13 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione', '0006_delete_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='copia',
            name='utente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='copie_in_prestito', to=settings.AUTH_USER_MODEL),
        ),
    ]
